# Generated by Django 4.1.1 on 2022-09-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='differential',
            field=models.FloatField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='inPressure',
            field=models.FloatField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='inflow',
            field=models.FloatField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='offset',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='outPressure',
            field=models.FloatField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='outflow',
            field=models.FloatField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='deviceinformation',
            name='temperature',
            field=models.FloatField(blank=True, max_length=1000),
        ),
    ]
