# Generated by Django 4.1.1 on 2022-10-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_deviceinformation_differential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=1000)),
                ('deviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deviceinformation')),
            ],
            options={
                'verbose_name_plural': 'Statuslist',
            },
        ),
    ]
