# Generated by Django 4.1.1 on 2022-10-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_statuslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(blank=True, max_length=1000)),
                ('inflow', models.FloatField(blank=True, max_length=1000)),
                ('outflow', models.FloatField(blank=True, max_length=1000)),
                ('inPressure', models.FloatField(blank=True, max_length=1000)),
                ('outPressure', models.FloatField(blank=True, max_length=1000)),
                ('temperature', models.FloatField(blank=True, max_length=1000)),
                ('differential', models.FloatField(blank=True, max_length=1000)),
                ('offset', models.FloatField(blank=True)),
                ('database_created_at', models.DateTimeField(auto_now_add=True)),
                ('database_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Information Log',
            },
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='deviceName',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
