# Generated by Django 4.1.1 on 2022-10-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_informationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuslist',
            old_name='deviceId',
            new_name='deviceName',
        ),
    ]
