# Generated by Django 4.1.1 on 2022-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_deviceid_statuslist_devicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='uploadDate',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Statuslist',
        ),
    ]
